import type * as Stitches from '@stitches/react'

export const DefaultTheme = {
  prefix: 'drift-dds',
  theme: {
    colors: {
      black: '#000000',
      white: '#FFFFFF',
      success: '$green8',
      successHover: '$green9',
      successActive: '$green10',
      danger: '$red8',
      dangerHover: '$red9',
      dangerActive: '$red10',
      education: '$purple8',
      educationHover: '$purple9',
      educationActive: '$purple10',
      warning: '$yellow8',
      warningHover: '$yellow9',
      warningActive: '$yellow10',
      subtleLink: '$gray8',
      subtleLinkHover: '$gray9',
      subtleLinkActive: '$gray10',
      inlineLink: '$blue8',
      inlineLinkHover: '$blue9',
      inlineLinkActive: '$blue10',
      primaryButtonText: '$white',
      secondaryButtonText: '$gray12',
      tertiaryButtonText: '$gray12',
      navItem: '$gray12',
      navItemActive: '$blue8',
      h1: '$gray12',
      h2: '$gray12',
      h3: '$gray12',
      h4: '$gray10',
      metric: '$gray12',
      subtitle1: '$gray10',
      subtitle2: '$gray10',
      metadata: '$gray10',
      body: '$gray12',
      bodyBold: '$gray12',
    },
    fonts: {
      primary:
        "'proxima', -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif",
    },
    sizes: {
      base: '8px',
      0: 0,
      half: 'calc($base / 2)',
      1: '$base',
      2: 'calc($base * 2)',
      3: 'calc($base * 3)',
      4: 'calc($base * 4)',
      5: 'calc($base * 5)',
      6: 'calc($base * 6)',
      7: 'calc($base * 7)',
      8: 'calc($base * 8)',
    },
    space: {
      base: '8px',
      0: 0,
      half: 'calc($base / 2)',
      1: '$base',
      2: 'calc($base * 2)',
      3: 'calc($base * 3)',
      4: 'calc($base * 4)',
      5: 'calc($base * 5)',
      6: 'calc($base * 6)',
      7: 'calc($base * 7)',
      8: 'calc($base * 8)',
    },
    fontSizes: {
      base: '14px',
      1: '0.857rem',
      2: '1rem',
      3: '1.143rem',
      4: '1.429rem',
      5: '1.714rem',
      6: '2.286rem',
      h1: '1.714rem',
      h2: '1.429rem',
      h3: '1.143rem',
      h4: '0.857rem',
      subtitle1: '1.143rem',
      subtitle2: '1rem',
      bodyBold: '1rem',
      body: '1rem',
      button1: '1rem',
      button2: '0.857rem',
      metadata: '0.857rem',
      metric: '2.857rem',
    },
    fontWeights: {
      lightest: 400,
      light: 400,
      normal: 400,
      semibold: 600,
      bold: 700,
      boldest: 700,
      h1: '$semibold',
      h2: '$normal',
      h3: '$semibold',
      h4: '$semibold',
      subtitle1: '$normal',
      subtitle2: '$normal',
      bodyBold: '$semibold',
      body: '$normal',
      button1: '$semibold',
      button2: '$semibold',
      metadata: '$normal',
      metric: '$semibold',
    },
    lineHeights: {
      base: '14px',
      h1: '2.571rem',
      h2: '2rem',
      h3: '1.714rem',
      h4: '1.143rem',
      subtitle1: '1.714rem',
      subtitle2: '1.429rem',
      bodyBold: '1.429rem',
      body: '1.429rem',
      button1: '1rem',
      button2: '1rem',
      metadata: '1.143rem',
      metric: '3.714rem',
    },
    letterSpacings: {
      base: '14px',
      h1: '-0.011rem',
      h2: '-0.011rem',
      h3: '-0.011rem',
      h4: '0.023rem',
      subtitle1: '-0.011rem',
      subtitle2: '-0.011rem',
      bodyBold: '-0.011rem',
      body: '-0.011rem',
      button1: '-0.011rem',
      button2: '-0.011rem',
      metadata: '-0.011rem',
      metric: '-0.011rem',
    },
    radii: {
      1: '3px',
      2: '6px',
      3: '8px',
      4: '12px',
      round: '50%',
    },
    shadows: {
      1: '0px 2px 1px -1px $colors$overlay5,0px 1px 1px 0px $colors$overlay4,0px 1px 3px 0px $colors$overlay3',
      2: '0px 3px 1px -2px $colors$overlay5,0px 2px 2px 0px $colors$overlay4,0px 1px 5px 0px $colors$overlay3',
      3: '0px 3px 3px -2px $colors$overlay5,0px 3px 4px 0px $colors$overlay4,0px 1px 8px 0px $colors$overlay3',
      4: '0px 2px 4px -1px $colors$overlay5,0px 4px 5px 0px $colors$overlay4,0px 1px 10px 0px $colors$overlay3',
      5: '0px 3px 5px -1px $colors$overlay5,0px 5px 8px 0px $colors$overlay4,0px 1px 14px 0px $colors$overlay3',
      6: '0px 3px 5px -1px $colors$overlay5,0px 6px 10px 0px $colors$overlay4,0px 1px 18px 0px $colors$overlay3',
      7: '0px 4px 5px -2px $colors$overlay5,0px 7px 10px 1px $colors$overlay4,0px 2px 16px 1px $colors$overlay3',
    },
    transitions: {
      transitionEaseInOut: '150ms cubic-bezier(0.4, 0, 0.2, 1) forwards',
      transitionEaseOut: 'cubic-bezier(0.0, 0, 0.2, 1)',
      transitionEaseIn: 'cubic-bezier(0.4, 0, 1, 1)',
      transitionSharp: 'cubic-bezier(0.4, 0, 0.6, 1)',
    },
    zIndices: {
      default: 800,
      nav: 1000,
      appBar: 1050,
      drawer: 1100,
      modal: 1200,
      snackbar: 1300,
      tooltip: 1400,
      max: 5000,
    },
  },
  media: {
    mobile: '(min-width: 576px)',
    tablet: '(min-width: 768px)',
    desktop: '(min-width: 992px)',
    largeScreen: '(min-width: 1200px)',
    motion: '(prefers-reduced-motion)',
    hover: '(any-hover: hover)',
    dark: '(prefers-color-scheme: dark)',
    light: '(prefers-color-scheme: light)',
  },
  utils: {
    marginX: (value: Stitches.PropertyValue<'marginLeft'>) => ({
      marginLeft: value,
      marginRight: value,
    }),
    dimensions: (value: Stitches.PropertyValue<'width'>) => ({
      width: value,
      height: value,
    }),
    textStyles: (variant: string) => ({
      fontSize: `$${variant}`,
      fontWeight: `$${variant}`,
      lineHeight: `$${variant}`,
      letterSpacing: `$${variant}`,
    }),
    textColor: (variant: string) => ({
      color: `$${variant}`,
    }),
  },
}
